export const DEFAULT_LABELS = {
  getcoins: 'Get Free Coins!',
  meme: 'Random Pepe',
  rarepepe: 'Rare Pepe',
  social: 'Create Social Media Post',
  socialShort: 'Social Post',
  communityart: 'Community Art',
  welcome: "Hello. I'm Professor Pepe, your AI agent. Type a command or choose one below.",
  placeholder: 'Type a command...',
}

export const LABELS = {
  German: {
    getcoins: 'Gratis Coins!',
    meme: 'Zufälliger Pepe',
    rarepepe: 'Rare Pepe',
    social: 'Social Media Post erstellen',
    socialShort: 'Post erstellen',
    communityart: 'Community Art',
    welcome: 'Hallo. Ich bin Professor Pepe, dein KI-Assistent. Tippe einen Befehl oder wähle unten einen aus.',
    placeholder: 'Befehl eingeben...',
  },
  Chinese: {
    getcoins: '领取免费币！',
    meme: '随机 Pepe',
    rarepepe: '稀有 Pepe',
    social: '创建社交媒体帖子',
    socialShort: '发帖子',
    welcome: '你好。我是 Professor Pepe，你的 AI 助手。输入命令或从下方选择一个。',
    placeholder: '输入命令...',
  },
  Hindi: {
    getcoins: 'मुफ्त सिक्के पाएं!',
    meme: 'रैंडम Pepe',
    rarepepe: 'रेयर Pepe',
    social: 'सोशल मीडिया पोस्ट बनाएं',
    socialShort: 'पोस्ट बनाएं',
    welcome: 'नमस्ते। मैं Professor Pepe हूँ, आपका AI एजेंट। एक कमांड टाइप करें या नीचे से एक चुनें।',
    placeholder: 'कोई कमांड टाइप करें...',
  },
  Spanish: {
    getcoins: '¡Consigue monedas gratis!',
    meme: 'Pepe aleatorio',
    rarepepe: 'Pepe raro',
    social: 'Crear publicación en redes sociales',
    socialShort: 'Crear publicación',
    welcome: 'Hola. Soy Professor Pepe, tu agente de IA. Escribe un comando o elige uno abajo.',
    placeholder: 'Escribe un comando...',
  },
  French: {
    getcoins: 'Obtenir des pièces gratuites !',
    meme: 'Pepe aléatoire',
    rarepepe: 'Pepe rare',
    social: 'Créer une publication sur les réseaux sociaux',
    socialShort: 'Créer un post',
    welcome: 'Bonjour. Je suis Professor Pepe, votre agent IA. Tapez une commande ou choisissez-en une ci-dessous.',
    placeholder: 'Tapez une commande...',
  },
  Arabic: {
    getcoins: 'احصل على عملات مجانية!',
    meme: 'Pepe عشوائي',
    rarepepe: 'Pepe نادر',
    social: 'إنشاء منشور على وسائل التواصل الاجتماعي',
    socialShort: 'إنشاء منشور',
    welcome: 'مرحبًا. أنا Professor Pepe، وكيلك الذكي. اكتب أمرًا أو اختر أحد الأوامر أدناه.',
    placeholder: 'اكتب أمرًا...',
  },
  Bengali: {
    getcoins: 'বিনামূল্যে কয়েন নিন!',
    meme: 'এলোমেলো Pepe',
    rarepepe: 'বিরল Pepe',
    social: 'সোশ্যাল মিডিয়া পোস্ট তৈরি করুন',
    socialShort: 'পোস্ট তৈরি করুন',
    welcome: 'হ্যালো। আমি Professor Pepe, আপনার AI এজেন্ট। একটি কমান্ড টাইপ করুন বা নিচে থেকে একটি বেছে নিন।',
    placeholder: 'একটি কমান্ড টাইপ করুন...',
  },
  Portuguese: {
    getcoins: 'Ganhar moedas grátis!',
    meme: 'Pepe aleatório',
    rarepepe: 'Pepe raro',
    social: 'Criar publicação nas redes sociais',
    socialShort: 'Criar publicação',
    welcome: 'Olá. Eu sou o Professor Pepe, seu agente de IA. Digite um comando ou escolha um abaixo.',
    placeholder: 'Digite um comando...',
  },
  Russian: {
    getcoins: 'Получить бесплатные монеты!',
    meme: 'Случайный Pepe',
    rarepepe: 'Редкий Pepe',
    social: 'Создать пост в социальных сетях',
    socialShort: 'Создать пост',
    welcome: 'Привет. Я Professor Pepe, ваш ИИ-агент. Введите команду или выберите одну из списка ниже.',
    placeholder: 'Введите команду...',
  },
  Urdu: {
    getcoins: 'مفت سکے حاصل کریں!',
    meme: 'بے ترتیب Pepe',
    rarepepe: 'نایاب Pepe',
    social: 'سوشل میڈیا پوسٹ بنائیں',
    socialShort: 'پوسٹ بنائیں',
    welcome: 'ہیلو۔ میں Professor Pepe ہوں، آپ کا AI ایجنٹ۔ ایک کمانڈ ٹائپ کریں یا نیچے سے ایک منتخب کریں۔',
    placeholder: 'ایک کمانڈ ٹائپ کریں...',
  },
  Indonesian: {
    getcoins: 'Dapatkan Koin Gratis!',
    meme: 'Pepe Acak',
    rarepepe: 'Pepe Langka',
    social: 'Buat Postingan Media Sosial',
    socialShort: 'Buat Postingan',
    welcome: 'Halo. Saya Professor Pepe, agen AI Anda. Ketik perintah atau pilih salah satu di bawah.',
    placeholder: 'Ketik perintah...',
  },
  Japanese: {
    getcoins: '無料コインをGET!',
    meme: 'ランダムPepe',
    rarepepe: 'レアPepe',
    social: 'SNS投稿を作成',
    socialShort: '投稿を作成',
    welcome: 'こんにちは。Professor Pepeです。あなたのAIエージェントです。コマンドを入力するか、下から選んでください。',
    placeholder: 'コマンドを入力...',
  },
  Marathi: {
    getcoins: 'मोफत नाणी मिळवा!',
    meme: 'यादृच्छिक Pepe',
    rarepepe: 'दुर्मिळ Pepe',
    social: 'सोशल मीडिया पोस्ट तयार करा',
    socialShort: 'पोस्ट तयार करा',
    welcome: 'नमस्कार. मी Professor Pepe आहे, तुमचा AI एजंट. एक कमांड टाइप करा किंवा खालीलपैकी एक निवडा.',
    placeholder: 'एक कमांड टाइप करा...',
  },
  Telugu: {
    getcoins: 'ఉచిత నాణేలను పొందండి!',
    meme: 'యాదృచ్ఛిక Pepe',
    rarepepe: 'అరుదైన Pepe',
    social: 'సోషల్ మీడియా పోస్ట్‌ను సృష్టించండి',
    socialShort: 'పోస్ట్ సృష్టించండి',
    welcome: 'హలో. నేను Professor Pepe, మీ AI ఏజెంట్. ఒక కమాండ్ టైప్ చేయండి లేదా కింద ఒకటిని ఎంచుకోండి.',
    placeholder: 'ఒక కమాండ్ టైప్ చేయండి...',
  },
  Turkish: {
    getcoins: 'Ücretsiz Coin Kazan!',
    meme: 'Rastgele Pepe',
    rarepepe: 'Nadir Pepe',
    social: 'Sosyal Medya Gönderisi Oluştur',
    socialShort: 'Gönderi Oluştur',
    welcome: 'Merhaba. Ben Professor Pepe, AI ajentiniz. Bir komut yazın veya aşağıdan birini seçin.',
    placeholder: 'Bir komut yazın...',
  },
  Tamil: {
    getcoins: 'இலவச நாணயங்களைப் பெறுங்கள்!',
    meme: 'சீரற்ற Pepe',
    rarepepe: 'அரிய Pepe',
    social: 'சமூக ஊடக இடுகையை உருவாக்கவும்',
    socialShort: 'இடுகையை உருவாக்கவும்',
    welcome: 'வணக்கம். நான் Professor Pepe, உங்கள் AI முகவர். ஒரு கட்டளையை தட்டச்சு செய்யவும் அல்லது கீழே ஒன்றைத் தேர்ந்தெடுக்கவும்.',
    placeholder: 'ஒரு கட்டளையை தட்டச்சு செய்யவும்...',
  },
  Vietnamese: {
    getcoins: 'Nhận Xu Miễn Phí!',
    meme: 'Pepe Ngẫu Nhiên',
    rarepepe: 'Pepe Hiếm',
    social: 'Tạo Bài Đăng Mạng Xã Hội',
    socialShort: 'Tạo Bài Đăng',
    welcome: 'Xin chào. Tôi là Professor Pepe, AI agent của bạn. Nhập lệnh hoặc chọn một lệnh bên dưới.',
    placeholder: 'Nhập lệnh...',
  },
  Korean: {
    getcoins: '무료 코인 받기!',
    meme: '랜덤 Pepe',
    rarepepe: '레어 Pepe',
    social: '소셜 미디어 게시물 만들기',
    socialShort: '게시물 만들기',
    welcome: '안녕하세요. Professor Pepe입니다. 당신의 AI 에이전트입니다. 명령어를 입력하거나 아래에서 선택하세요.',
    placeholder: '명령어 입력...',
  },
  Italian: {
    getcoins: 'Ottieni Monete Gratis!',
    meme: 'Pepe Casuale',
    rarepepe: 'Pepe Raro',
    social: 'Crea Post sui Social Media',
    socialShort: 'Crea Post',
    welcome: 'Ciao. Sono Professor Pepe, il tuo agente AI. Digita un comando o scegline uno qui sotto.',
    placeholder: 'Digita un comando...',
  },
}

export function getLabels(language) {
  return LABELS[language] || DEFAULT_LABELS
}
